apiVersion: v1
kind: Service
metadata:
  name: express-socket-server-service
spec:
  selector:
    app: express-socket-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
